-- Allow valid IDs to be inserted manually
ALTER TABLE settings ALTER COLUMN id SET GENERATED BY DEFAULT;

-- Insert the initial settings row (using only guaranteed columns)
INSERT INTO settings (id, provider)
VALUES (1, 'gemini')
ON CONFLICT (id) DO NOTHING;
