-- The error "cannot insert a non-DEFAULT value" happens when a column is "GENERATED ALWAYS".
-- We need to change it to "GENERATED BY DEFAULT" so we can force id=1.

-- Option 1: Valid for Postgres 10+ (Supabase Standard)
ALTER TABLE settings ALTER COLUMN id SET GENERATED BY DEFAULT;

-- Ensure row 1 exists (optional, but good for initialization)
INSERT INTO settings (id, provider, created_at)
VALUES (1, 'gemini', now())
ON CONFLICT (id) DO NOTHING;
