[build]
  command = "cd client && npm install && CI=false npm run build"
  publish = "client/dist"

[functions]
  directory = "server"

# Redirects for Single Page App
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy /api requests to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
