[build]
  command = "npm install --prefix server && npm install --prefix client && npm run build --prefix client"
  publish = "client/dist"

[functions]
  directory = "server"

# Redirects for Single Page App
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy /api requests to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
